/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as FotografieCulinaraBucurestiRouteImport } from './routes/fotografie-culinara-bucuresti'
import { Route as FoodRouteImport } from './routes/food'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as AdminThemeRouteImport } from './routes/admin.theme'
import { Route as AdminSocialsRouteImport } from './routes/admin.socials'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminPerformanceRouteImport } from './routes/admin.performance'
import { Route as AdminLinksRouteImport } from './routes/admin.links'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminAssetsRouteImport } from './routes/admin.assets'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiDebugR2RouteImport } from './routes/api/debug/r2'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const FotografieCulinaraBucurestiRoute =
  FotografieCulinaraBucurestiRouteImport.update({
    id: '/fotografie-culinara-bucuresti',
    path: '/fotografie-culinara-bucuresti',
    getParentRoute: () => rootRouteImport,
  } as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/admin/theme',
  path: '/admin/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSocialsRoute = AdminSocialsRouteImport.update({
  id: '/admin/socials',
  path: '/admin/socials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPerformanceRoute = AdminPerformanceRouteImport.update({
  id: '/admin/performance',
  path: '/admin/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/admin/links',
  path: '/admin/links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssetsRoute = AdminAssetsRouteImport.update({
  id: '/admin/assets',
  path: '/admin/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugR2Route = ApiDebugR2RouteImport.update({
  id: '/api/debug/r2',
  path: '/api/debug/r2',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/editorial': typeof EditorialRoute
  '/food': typeof FoodRoute
  '/fotografie-culinara-bucuresti': typeof FotografieCulinaraBucurestiRoute
  '/patterns': typeof PatternsRoute
  '/people': typeof PeopleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video': typeof VideoRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/socials': typeof AdminSocialsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/work/$slug': typeof WorkSlugRoute
  '/api/debug/r2': typeof ApiDebugR2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/editorial': typeof EditorialRoute
  '/food': typeof FoodRoute
  '/fotografie-culinara-bucuresti': typeof FotografieCulinaraBucurestiRoute
  '/patterns': typeof PatternsRoute
  '/people': typeof PeopleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video': typeof VideoRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/socials': typeof AdminSocialsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/work/$slug': typeof WorkSlugRoute
  '/api/debug/r2': typeof ApiDebugR2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/editorial': typeof EditorialRoute
  '/food': typeof FoodRoute
  '/fotografie-culinara-bucuresti': typeof FotografieCulinaraBucurestiRoute
  '/patterns': typeof PatternsRoute
  '/people': typeof PeopleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video': typeof VideoRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/socials': typeof AdminSocialsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/work/$slug': typeof WorkSlugRoute
  '/api/debug/r2': typeof ApiDebugR2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/editorial'
    | '/food'
    | '/fotografie-culinara-bucuresti'
    | '/patterns'
    | '/people'
    | '/sitemap.xml'
    | '/video'
    | '/admin/analytics'
    | '/admin/assets'
    | '/admin/contacts'
    | '/admin/links'
    | '/admin/performance'
    | '/admin/seo'
    | '/admin/socials'
    | '/admin/theme'
    | '/work/$slug'
    | '/api/debug/r2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/editorial'
    | '/food'
    | '/fotografie-culinara-bucuresti'
    | '/patterns'
    | '/people'
    | '/sitemap.xml'
    | '/video'
    | '/admin/analytics'
    | '/admin/assets'
    | '/admin/contacts'
    | '/admin/links'
    | '/admin/performance'
    | '/admin/seo'
    | '/admin/socials'
    | '/admin/theme'
    | '/work/$slug'
    | '/api/debug/r2'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contact'
    | '/editorial'
    | '/food'
    | '/fotografie-culinara-bucuresti'
    | '/patterns'
    | '/people'
    | '/sitemap.xml'
    | '/video'
    | '/admin/analytics'
    | '/admin/assets'
    | '/admin/contacts'
    | '/admin/links'
    | '/admin/performance'
    | '/admin/seo'
    | '/admin/socials'
    | '/admin/theme'
    | '/work/$slug'
    | '/api/debug/r2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EditorialRoute: typeof EditorialRoute
  FoodRoute: typeof FoodRoute
  FotografieCulinaraBucurestiRoute: typeof FotografieCulinaraBucurestiRoute
  PatternsRoute: typeof PatternsRoute
  PeopleRoute: typeof PeopleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VideoRoute: typeof VideoRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAssetsRoute: typeof AdminAssetsRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminPerformanceRoute: typeof AdminPerformanceRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSocialsRoute: typeof AdminSocialsRoute
  AdminThemeRoute: typeof AdminThemeRoute
  WorkSlugRoute: typeof WorkSlugRoute
  ApiDebugR2Route: typeof ApiDebugR2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografie-culinara-bucuresti': {
      id: '/fotografie-culinara-bucuresti'
      path: '/fotografie-culinara-bucuresti'
      fullPath: '/fotografie-culinara-bucuresti'
      preLoaderRoute: typeof FotografieCulinaraBucurestiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/admin/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/socials': {
      id: '/admin/socials'
      path: '/admin/socials'
      fullPath: '/admin/socials'
      preLoaderRoute: typeof AdminSocialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/performance': {
      id: '/admin/performance'
      path: '/admin/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AdminPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/admin/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assets': {
      id: '/admin/assets'
      path: '/admin/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AdminAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/r2': {
      id: '/api/debug/r2'
      path: '/api/debug/r2'
      fullPath: '/api/debug/r2'
      preLoaderRoute: typeof ApiDebugR2RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EditorialRoute: EditorialRoute,
  FoodRoute: FoodRoute,
  FotografieCulinaraBucurestiRoute: FotografieCulinaraBucurestiRoute,
  PatternsRoute: PatternsRoute,
  PeopleRoute: PeopleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VideoRoute: VideoRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAssetsRoute: AdminAssetsRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminPerformanceRoute: AdminPerformanceRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSocialsRoute: AdminSocialsRoute,
  AdminThemeRoute: AdminThemeRoute,
  WorkSlugRoute: WorkSlugRoute,
  ApiDebugR2Route: ApiDebugR2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
